name: Test
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Build theme and docs
        run: pnpm docs:build

      - name: Linter
        run: pnpm lint

      - name: Unit test
        run: pnpm test:unit

      - name: E2E test
        run: pnpm test:e2e
